"""Storage for individual survey responses to be included in the appendix."""

SURVEY_RESPONSES = [
    {
        "id": 1,
        "trader_name": "Mayuri Ladies Corner",
        "business_type": "Retail / Trading",
        "years_in_operation": "Above 10 Years",
        "annual_turnover": "Below Rs. 20 Lakh",
        "gst_scheme": "Regular Scheme",
        "awareness": "Yes",
        "manages_filing": "Self",
        "frequency": "Monthly",
        "digital_records": "No",
        "workshop": "No",
        "tax_burden": "Increased",
        "operating_cost": "Yes",
        "itc_claimed": "No",
        "pricing_effect": "Increased",
        "profit_impact": "Negatively",
        "photo_path": "respondent_1_photo.jpg",
        "handwriting_path": "respondent_1_answers.png"
    },
    {
        "id": 2,
        "trader_name": "Sowmya matching center",
        "business_type": "Retail",
        "years_in_operation": "Above 20 Years",
        "annual_turnover": "Rs. 10 Lakhs",
        "gst_scheme": "Regular scheme",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Quarterly",
        "digital_records": "No Digital",
        "workshop": "N/A",  # Not in list but mapped
        "tax_burden": "Increase",
        "operating_cost": "Yes",
        "itc_claimed": "N/A",  # Not in list but mapped
        "pricing_effect": "No change",
        "profit_impact": "Negatively",
        "photo_path": "respondent_2_photo.jpg",
        "handwriting_path": "respondent_2_answers.png"
    },
    {
        "id": 3,
        "trader_name": "Ganesh Krupa Kirana Agency",
        "business_type": "Whole Retail",
        "years_in_operation": "Below 5 Year",
        "annual_turnover": "Above Rs 75 Lakh",
        "gst_scheme": "Regular",
        "awareness": "Yes",
        "manages_filing": "Self",
        "frequency": "Monthly",
        "digital_records": "No",
        "workshop": "Yes",
        "tax_burden": "Decrease",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_3_photo.jpg",
        "handwriting_path": "respondent_3_answers.png"
    },
    {
        "id": 4,
        "trader_name": "Famous Footwear",
        "business_type": "Retail",
        "years_in_operation": "40 Yr",
        "annual_turnover": "20 L",
        "gst_scheme": "Regular",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Annualy",
        "digital_records": "No digital records",
        "workshop": "N/A",
        "tax_burden": "Same",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_4_photo.jpg",
        "handwriting_path": "respondent_4_answers.png"
    },
    {
        "id": 5,
        "trader_name": "Venkatramana Jewellery",
        "business_type": "Retail",
        "years_in_operation": "Above 20 yr",
        "annual_turnover": "75 L",
        "gst_scheme": "Regular",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Quarterly",
        "digital_records": "Yes",
        "workshop": "N/A",
        "tax_burden": "N/A",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_5_photo.jpg",
        "handwriting_path": "respondent_5_answers.png"
    },
    {
        "id": 6,
        "trader_name": "Manoranjani Electronics",
        "business_type": "Retail",
        "years_in_operation": "27 yrs",
        "annual_turnover": "3 Lakh",
        "gst_scheme": "Regular",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Quarterly",
        "digital_records": "No Digital",
        "workshop": "Yes",
        "tax_burden": "Remains same",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_6_photo.png",
        "handwriting_path": "respondent_6_answers.png"
    },
    {
        "id": 7,
        "trader_name": "Venkatramana Shopping Mall",
        "business_type": "Retail",
        "years_in_operation": "42 yr",
        "annual_turnover": "Above 75 L",
        "gst_scheme": "Regular",
        "awareness": "Yes (CGST)",
        "manages_filing": "CA",
        "frequency": "Monthly",
        "digital_records": "Yes Digital records",
        "workshop": "N/A",
        "tax_burden": "Loss on tax burden",
        "operating_cost": "Yes",
        "itc_claimed": "Yes",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_7_photo.jpg",
        "handwriting_path": "respondent_7_answers.png"
    },
    {
        "id": 8,
        "trader_name": "Sai Sudha Homeneeds",
        "business_type": "Retail Wholesale",
        "years_in_operation": "50 yrs",
        "annual_turnover": "Above 75 L",
        "gst_scheme": "Regular",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Monthly",
        "digital_records": "Yes - Digital records",
        "workshop": "N/A",
        "tax_burden": "N/A",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "Positively",
        "photo_path": "respondent_8_photo.jpg",
        "handwriting_path": "respondent_8_answers.png"
    },
    {
        "id": 9,
        "trader_name": "Pruthvi Polymers",
        "business_type": "Manufacturing",
        "years_in_operation": "Below 5 yr",
        "annual_turnover": "4 Cr",
        "gst_scheme": "Regular 18%",
        "awareness": "SGST - Yes",
        "manages_filing": "CA",
        "frequency": "Monthly",
        "digital_records": "Yes - Digital",
        "workshop": "No",
        "tax_burden": "same",
        "operating_cost": "same",
        "itc_claimed": "N/A",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_9_photo.jpg",
        "handwriting_path": "respondent_9_answers.png"
    },
    {
        "id": 10,
        "trader_name": "G.R. Electronics",
        "business_type": "Retail (Electronics)",
        "years_in_operation": "10 yr",
        "annual_turnover": "20 - 75 L",
        "gst_scheme": "Regular",
        "awareness": "GST - Yes",
        "manages_filing": "Accountant",
        "frequency": "Monthly",
        "digital_records": "N/A",
        "workshop": "Yes",
        "tax_burden": "Increases",
        "operating_cost": "Yes",
        "itc_claimed": "N/A",
        "pricing_effect": "Yes",
        "profit_impact": "N/A",
        "photo_path": "respondent_10_photo.jpg",
        "handwriting_path": "respondent_10_answers.png"
    },
    {
        "id": 11,
        "trader_name": "TITAN ZEAIN WATCHES",
        "business_type": "Retail",
        "years_in_operation": "Above 10 years",
        "annual_turnover": "Above 75 L",
        "gst_scheme": "Composition scheme",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Quarterly",
        "digital_records": "Digital Yes",
        "workshop": "workshop yes",
        "tax_burden": "same",
        "operating_cost": "Increasing",
        "itc_claimed": "No",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_11_photo.jpg",
        "handwriting_path": "respondent_11_answers.png"
    },
    {
        "id": 12,
        "trader_name": "7 Star Paints",
        "business_type": "Retail",
        "years_in_operation": "Below 5 Year",
        "annual_turnover": "70 Lakhs",
        "gst_scheme": "Regular",
        "awareness": "No",
        "manages_filing": "CA",
        "frequency": "Monthly",
        "digital_records": "No",
        "workshop": "Yes",
        "tax_burden": "Same",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "No",
        "profit_impact": "N/A",
        "photo_path": "respondent_12_photo.jpg",
        "handwriting_path": "respondent_12_answers.png"
    },
    {
        "id": 13,
        "trader_name": "Sri Venkatramana Traders",
        "business_type": "Wholesale",
        "years_in_operation": "Below 5 yr",
        "annual_turnover": "Above 75 L",
        "gst_scheme": "Regular scheme",
        "awareness": "CGST - Yes",
        "manages_filing": "CA",
        "frequency": "Monthly",
        "digital_records": "Digital - Yes",
        "workshop": "Workshop - Yes",
        "tax_burden": "Same - No Loss No Profit",
        "operating_cost": "N/A",
        "itc_claimed": "No",
        "pricing_effect": "N/A",
        "profit_impact": "N/A",
        "photo_path": "respondent_13_photo.jpg",
        "handwriting_path": "respondent_13_answers.png"
    },
    {
        "id": 14,
        "trader_name": "Sri Lakshmi Flowers & Pooja Stores",
        "business_type": "Wholesale",
        "years_in_operation": "60 Yrs",
        "annual_turnover": "Below 20 L",
        "gst_scheme": "Regular",
        "awareness": "No",
        "manages_filing": "CA",
        "frequency": "Annualy",
        "digital_records": "No",
        "workshop": "Yes",
        "tax_burden": "Same",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "No",
        "profit_impact": "N/A",
        "photo_path": "respondent_14_photo.jpg",
        "handwriting_path": "respondent_14_answers.png"
    },
    {
        "id": 15,
        "trader_name": "Jaswitha Pharmacy",
        "business_type": "Retail",
        "years_in_operation": "Below 5 yrs",
        "annual_turnover": "Below 20 Lakhs",
        "gst_scheme": "Composition scheme",
        "awareness": "Yes",
        "manages_filing": "CA",
        "frequency": "Regular",
        "digital_records": "No - Digital",
        "workshop": "Yes - Workshop",
        "tax_burden": "Loss",
        "operating_cost": "N/A",
        "itc_claimed": "N/A",
        "pricing_effect": "Yes",
        "profit_impact": "N/A",
        "photo_path": "respondent_15_photo.jpg",
        "handwriting_path": "respondent_15_answers.png"
    }
]
